safe:        false
auto:        false
server:      false
baseurl:     /

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   pretty
